#!/usr/bin/env python
import sys

from fitch_app import toplevel
toplevel.install()

import main
import app

app.instantiate()
main.main()

sys.excepthook = app.excepthook # Show Python errors in a bugreport window

sys.exit(app.run())
